### ISSUE TITLE
API Status with Disconnect of Ecobee (Connect)

### ISSUE THREAD

**Issue by ncsufire** [StrykerSKS/SmartThingsPublic#20]
I received an ST alert stating that my Ecobee had disconnected but in the recently log it showed the apiConnected = full.  I hit refresh on the thermostat and received a debugEvent.  The attached image came from the phone app.
![screenshot_2016-01-27-15-24-53](https://cloud.githubusercontent.com/assets/16526555/12627228/b5bcf126-c50a-11e5-95b5-9a57fa664a74.png)

**Comment by StrykerSKS** [comment]
This is a race condition in the way that events get sent through the ST platform, so it is possible for events to arrive out of order. Nothing I can really do to prevent this from happening but it does eventually get to the right state if you manually refresh.

If you refresh the app again you should see that the API is lost. I only send the apiLost event when the connection is unrepairable. In all other cases of a temporary error I use "warn" instead of "lost" for the API status. 

The platform is still having ongoing issues with Scheduled Events. This is a ST platform issue.

I am currently working on some additional hooks that will make it a little more robust to these platform issues, but if the schedulers fail on the platform side it will eventually impact the API connection.
