### ISSUE TITLE
Ecobee Thermostat Display in Things

### ISSUE THREAD

**Issue by ncsufire** [StrykerSKS/SmartThingsPublic#3]
On Android phone the thermostat shows up with a ? mark.  I am on a Samsung Galaxy S5 using 3.4.0 Kernel with Android 5.0

![screenshot_2016-01-03-09-45-23](https://cloud.githubusercontent.com/assets/16526555/12079215/efeba122-b1fe-11e5-8ccb-805e56c81a81.png)

**Comment by StrykerSKS** [comment]
Okay, I was worried about differences between the two platforms. A couple of questions to try to track down:
- I am using a multiAttributeTile for the main display and control of the vital thermostat information. Do you have any other devices using multiAttributeTile? If so, are they working properly? (More information on [multiAttributeTile()'s here](http://docs.smartthings.com/en/latest/device-type-developers-guide/tiles-metadata.html)
- If you click on the question marks does the device open with data?

Another interesting difference with your screenshot vs iOS, it is showing a decimal after the value instead of just the integer value. On iOS it does not show the decimal values in the main screen.

Can you test something for me? If you go into the Ecobee Thermostat code and edit the following:

> main "summary"

and make it instead

> main "temperature"

This will change which tile is used to render on the Things screen. It might help us isolate what is causing the question mark. 

Finally, can you go into "My Devices" in the IDE and select a thermostat and see if there is anything there that looks strange?

**Comment by ncsufire** [comment]
No the only customized devices I have use the standard tile.  When I click on the ? mark it does go into the device, I have included a screen shot.  I did see this when reading about the multiple attribute tiles in the link you sent "Currently there is a parity issue between Android and iOS platforms in regard to how multiAttribute tiles work. There is currently work being done on the Android platform to address this. In the meantime, some things stated here about multiAttributeTiles may not work as expectd on the Android platform."

![screenshot_2016-01-03-14-12-25](https://cloud.githubusercontent.com/assets/16526555/12080292/40e701be-b224-11e5-8314-8305508e1c54.png)

When I changed to main "temperature" the question mark went away and it now displays properly
![screenshot_2016-01-03-14-17-59](https://cloud.githubusercontent.com/assets/16526555/12080321/077bfa50-b225-11e5-8c1e-dea3d03c49a4.png)

In the IDE I do not see anything that is strange, anything in particular I should be looking for?  I will tell you before making the change from "summary" to "temperature" I was getting an error on the App that seems to have gone away.

**Comment by ncsufire** [comment]
The main question mark is still on my screen even with the above mentioned changes.

**Comment by JuraasicCoasterNerd** [comment]
I can confirm changing the code resolves the issue with the question mark in the app listing. 

However, it does not resolve the main tile in the app showing a question mark. I also dont see how i can change the temp from the application.

**Comment by StrykerSKS** [comment]
I've just uploaded a new version that should fix this issue.

Please update and test to see if this works for you.

**Comment by ncsufire** [comment]
When I went to check and see if I needed to real synicate I got the
following error
"{"error":true,"type":"java.lang.reflect.UndeclaredThrowableException","message":"An
unexpected error occurred."}"

**Comment by ncsufire** [comment]
I updated through the GitHub but I am not able to control using the arrows and the temperature is not refreshing.  I also got a disconnect notice at 8:03am.  I tried to connect and got an error "java.lang.reflect.UndeclaredThrowableException", "message": "An unexpected error occurred".

**Comment by ncsufire** [comment]
I had some issues doing the automatic update from GitHub so I did a delete and manual reinstall.  LOOKS GOOD!  A couple items I noticed during the functional testing:

The Operating State tile at one point showed both the "Fan Only and Heat" overlayed on top of each other during testing (I couldn't get a screen shot).  I noticed that there was about a 2 minute delay from the change of temperature and operation at the thermostat (from the app) and the update of the tile.  Not sure if this is a Ecobee/SmartThings issue.

The arrows to the left of the temperature did not change the status of the thermostat to cause it to run.  The slide bar at the bottom of the program did though.

**Comment by StrykerSKS** [comment]
Not sure why there would be a problem doing the auto update. I've successfully used it many times with both my own code and from other repositories. Sorry it didn't work for you.

On the Operating State, this had to be a glitch in the client side. The "tile" defined for Operating State only has a few distinct states and can only be in one state at a time. So any overlap must have been an issue with the client app. Here is what is in the code:

>   standardTile("operatingState", "device.thermostatOperatingState", width: 2, height: 2, inactiveLabel: false, decoration: "flat") {
>             state "idle", label: "Idle", backgroundColor:"#44b621", icon: "st.nest.empty"
>             state "heating", backgroundColor:"#ffa81e", icon: "st.thermostat.heat"
>             state "cooling", backgroundColor:"#269bd2", icon: "st.thermostat.cool"
>             state "default", label: '${currentValue}'
>         }

Fan Only is not one of the options even. So are you sure you were looking at the Operating State tile? Perhaps it was the "mode" tile?

Regarding the delay between making a change and action at the thermostat, I haven't seen that. For me it has always taken less than 10 seconds between issuing the command and it taking effect at the thermostat. In fact, I often test with the Ecobee website open in a separate tab to watch the changes hit their portal. I have no idea what would be causing that delay.

And finally, regarding the arrows in the multiAttribute tile, this is related to the bug impacting Android which is why I added the sliders (although I really like the sliders now that I added them so will keep them even after the bug is fixed). Once the bug is fixed I'll switch back to a Thermometer multiAttributeTile.

**Comment by ncsufire** [comment]
No problem on the auto update, manual code adoption is easy enough and I
think the issue was on my end.

I believe it was the operating tile, on my app it is the row directly under
the temperature tile on the far left.  By the time I tried to screen shot
it, it was gone.

I apologize as I was not clear in what I was saying.  The delay was not in
the change of temperature from the app to the thermostat, it was the delay
in updating of the Operating tile.  For example, when I would change from
Idle to Heat (turning up the temperature), the Operating tile stayed Idle
for approximately two minutes and then the status changed.  I even tried to
hit update a few times.

I understand about the arrows, I thought they might have been fixed which
is why I pointed them out.  I like the slider as well and wouldn't mind it
staying.

If I am not clear on any of this please let me know.

On Mon, Jan 4, 2016 at 9:10 PM, Sean Schneyer notifications@github.com
wrote:

> Not sure why there would be a problem doing the auto update. I've
> successfully used it many times with both my own code and from other
> repositories. Sorry it didn't work for you.
> 
> On the Operating State, this had to be a glitch in the client side. The
> "tile" defined for Operating State only has a few distinct states and can
> only be in one state at a time. So any overlap must have been an issue with
> the client app. Here is what is in the code:
> 
> standardTile("operatingState", "device.thermostatOperatingState", width:
> 2, height: 2, inactiveLabel: false, decoration: "flat") {
> state "idle", label: "Idle", backgroundColor:"#44b621", icon:
> "st.nest.empty"
> state "heating", backgroundColor:"#ffa81e", icon: "st.thermostat.heat"
> state "cooling", backgroundColor:"#269bd2", icon: "st.thermostat.cool"
> state "default", label: '${currentValue}'
> }
> 
> Fan Only is not one of the options even. So are you sure you were looking
> at the Operating State tile? Perhaps it was the "mode" tile?
> 
> Regarding the delay between making a change and action at the thermostat,
> I haven't seen that. For me it has always taken less than 10 seconds
> between issuing the command and it taking effect at the thermostat. In
> fact, I often test with the Ecobee website open in a separate tab to watch
> the changes hit their portal. I have no idea what would be causing that
> delay.
> 
> And finally, regarding the arrows in the multiAttribute tile, this is
> related to the bug impacting Android which is why I added the sliders
> (although I really like the sliders now that I added them so will keep them
> even after the bug is fixed). Once the bug is fixed I'll switch back to a
> Thermometer multiAttributeTile.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StrykerSKS/SmartThingsPublic/issues/3#issuecomment-168872236
> .

## 

John Lemire

**Comment by ncsufire** [comment]
Here are the screen shots of the Operating Tile and the overlap and then the Fan Only.  Here is what was happening.  The thermostat was running in heat mote.  My thermostat is setup such that when the Heat (or A/C) turns off the fan will run for 30 or so seconds to blow the remaining hot (or cold) air from the ducts into the house.  As soon as I heard the thermostat click off I refreshed the thermostat in the Smart Apps and got this:
![screenshot 1](https://cloud.githubusercontent.com/assets/16526555/12132750/f8395172-b3ec-11e5-8c43-58f9fabe8a55.png)
After 20 or so seconds I refreshed and got this:
![screenshot 2](https://cloud.githubusercontent.com/assets/16526555/12132754/05321f58-b3ed-11e5-8ef2-55bbb3f4d048.png)
Here is the log of events from Recent
![events](https://cloud.githubusercontent.com/assets/16526555/12132761/11b55d1c-b3ed-11e5-9b37-56379660f4ed.png)

**Comment by StrykerSKS** [comment]
Okay, I think I know what is causing the overlap. There is a catchall default that just puts the label on but doesn't use an icon, so it is keep in the original icon from the last mode and just writing over it. I'll have to see if I can use an empty icon to remove the icon on there.

**Comment by StrykerSKS** [comment]
Can we close out this issue which was really about the Question marks, which I have fixed and open up a separate one to track the overlap? And if there are any other issues that have shown up in our comments, please open those as separate issues so that we can track and hopefully close each of them with solutions.

**Comment by ncsufire** [comment]
Sure
