### ISSUE TITLE
Stuck on install

### ISSUE THREAD

**Issue by Bboy486** [StrykerSKS/SmartThingsPublic#78]
I get stuck on the routines app. It just says Setup Routines but I can't do anything. Oath is enabled.

**Comment by Bboy486** [comment]
7:32:38 PM: error java.lang.NullPointerException: Cannot invoke method LOG() on null object @ line 240

**Comment by StrykerSKS** [comment]
Are you trying to install the Routines app directly or from within the Ecobee Connect app?

**Comment by Bboy486** [comment]
Directly. I uninstalled and reinstalled. This is the error I get:

physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'Ecobee Thermostat' in namespace 'StrykerSKS' not found. @ line 463

**Comment by StrykerSKS** [comment]
You can't install directly. It is a child app and is launched from the Connect app.

**Comment by Bboy486** [comment]
Got it. Started over and I can't get past the pref part of the smartapp install it has lorem ipsum otherpref and errors

 7:34:55 AM: error physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'Ecobee Thermostat' in namespace 'StrykerSKS' not found. @ line 463

**Comment by StrykerSKS** [comment]
Have you followed the instructions in the Readme? 

https://github.com/StrykerSKS/SmartThingsPublic/blob/StrykerSKS-Ecobee3/smartapps/smartthings/ecobee-connect.src/README.md

**Comment by Bboy486** [comment]
Yes I did

**Comment by StrykerSKS** [comment]
Can you please give me a step by step of what you are doing just prior to receiving the error?

The UnkownDeviceType makes it look like you have not properly installed the Thermostat device type at that point, which would mean that you did not go through the full steps of installing the thermostat.

You have to install the thermostat device type and setup the thermostat via the Connect app before proceeding to use one of the child apps.

**Comment by Bboy486** [comment]
. Sure. So I install the smart app for the thermostat and routine as well as the two device types. 

I enable Oauth on the main smart app.

 Then I go into my SmartThings app go to smart apps > my app >  and click on ecobee connect .

 It asked me to sign into my ecobee account I do that then I go back to the previous screen and click done

 Then I go to the smart app under smart apps connect the thermostat, it asked me if I have any sensors which I do not, and then I get the Loram Epsum otherpref and when I click done  I get the green verification that is automating and then a few seconds later I get the read error message

**Comment by StrykerSKS** [comment]
I'm at a complete loss here. There is nothing in my code that could produce a Lorem Ipsum response that I could find. 

What version does the Connect app show that you are using? 

Also, are you on a full Ecobee 3 or do you have the Ecobee 3 Lite version?

**Comment by Bboy486** [comment]
*	Date: 2013-08-07
Ecobee Lite 3

**Comment by Bboy486** [comment]
Not sure how to tell I pulled from the GitHub site
 *      JLH - 02-15-2014 - Fuller use of ecobee API

**Comment by Bboy486** [comment]
I started from scratch. Deleted everything. Blank canvas. 

Pulled from repo.

OAuth on Smartapp.

Got a different screen. Looked like it should -no lorem Ipsum. 

Set up polling and watchdog for an iris sensor. Picked my thermo.

Went to click done

Error

------  9:57:16 AM: error refreshAuthToken(), General Exception: java.lang.NullPointerException: Cannot get property '---' on null object.

**Comment by StrykerSKS** [comment]
The Lite is not yet supported.

**Comment by thale57** [comment]
This answered my problem. Looking forward to the Lite being supported

**Comment by Bboy486** [comment]
Well that explains it. Are you planning on supporting it?

**Comment by thale57** [comment]
Bboy486, I played around with it this weekend and got mine to work. Wrote up some instructions after replicating my success a couple times. Hope it helps! I'm now able to auto-set the thermostat mode based on my home mode, which is ultimately what I was looking for.

1. Make the following changes in the Ecobee (Connect) app
Comment out lines 1156 and 1180
- 1156: oneChild.generateEvent(atomicState.thermostats[oneChild.device.deviceNetworkId]?.data)
- 1180: atomicState.thermostats[oneChild.device.deviceNetworkId]?.data?.apiConnected = apiConnected()

Change line 1195 so that "includeSensors" is false
- 1195: def jsonRequestBody = '{"selection":{"selectionType":"thermostats","selectionMatch":"' + thermostatIdsString + '","includeExtendedRuntime":"false","includeSettings":"true","includeRuntime":"true","includeEquipmentStatus":"true","includeSensors":"false","includeWeather":"true","includeProgram":"true","includeAlerts":"true","includeEvents":"true"}}'

2. Set up the Ecobee Connect app in SmartThings. Ignore the sensors settings page, but select your thermostat(s) in the Thermostats settings page

3. At this point, I checked to make sure the thermostats were showing up in my Things. There will be no data loaded

4. Update the Ecobee (Connect) app to uncomment out lines 1156 and 1180. Keep the change to line 1195.

5. Go back to your thermostat(s) and make sure data is coming in. Then you can set up routines, etc.

**Comment by Bboy486** [comment]
Thanks
